export const actions = {
  CHANGE_FILTRO_FIELD: "CHANGE_FILTRO_FIELD",
  CHANGE_FILTRO_VALUE: "CHANGE_FILTRO_VALUE",
  CHANGE_FILTRO_SHOW_DEACTIVE: "CHANGE_FILTRO_SHOW_DEACTIVE",
  FILTER_RESULTS: "FILTER_RESULTS",
  CLEAN_FILTRO: "CLEAN_FILTRO",
  CHANGE_PAGE: "CHANGE_PAGE",
  CHANGE_IN_PAGE: "CHANGE_IN_PAGE",
  CHANGE_TOTAL_PAGES: "CHANGE_TOTAL_PAGES",
  CHANGE_TOTAL_ELEMENTS: "CHANGE_TOTAL_ELEMENTS",
  CHANGE_SORT_FIELD: "CHANGE_SORT_FIELD",
  CHANGE_SORT_ASC: "CHANGE_SORT_ASC",
  TOGGLE_ASC: "TOGGLE_ASC"
};