export const ACTIONS = {
    CHANGE_TITLE: "CHANGE_TITLE",
    CHANGE_BODY: "CHANGE_BODY",
    SHOW: "SHOW",
    HIDE: "HIDE",
    SUCCESS: "SUCCESS",
    DANGER: "DANGER",
    WARNING: "WARNING",
    SET_ON_YES_NO: "SET_ON_YES_NO",
    SET_QUESTION: "SET_QUESTION"
}